### ISSUE TITLE
Static Analyzer: Dereference of null pointer (loaded from variable 'paneLocation')

### ISSUE THREAD

**Issue by Timac** [erichoracek/MSDynamicsDrawerViewController#82]
The Clang Static Analyzer reports 3 warnings in MSDynamicsDrawerViewController.m caused by the dereference of the 'paneLocation' variable:

MSDynamicsDrawerViewController/MSDynamicsDrawerViewController.m:730:13: warning: Dereference of null pointer (loaded from variable 'paneLocation')
        if (_paneLocation >= *openWideLocation) {
            ^~~~~~~~~~~~~
MSDynamicsDrawerViewController/MSDynamicsDrawerViewController.m:734:13: warning: Dereference of null pointer (loaded from variable 'paneLocation')
        if (_paneLocation <= _openWideLocation) {
            ^~~~~~~~~~~~~
MSDynamicsDrawerViewController/MSDynamicsDrawerViewController.m:1081:9: warning: Dereference of null pointer (loaded from variable 'paneLocation')
    if (_paneLocation <= paneBoundClosedLocation) {
        ^~~~~~~~~~~~~
3 warnings generated.

These warnings could be fixed by simply doing:
 if (paneLocation && (*paneLocation <= xxxxxxxxx))

**Comment by erichoracek** [comment]
Fixed in 1e85b023401e83d63036106ef4386eea55c8f735. Good catch!

**Comment by erichoracek** [comment]
Also of note—the `NULL` pointer dereference would be impossible to reach due to the conditionals surrounding it. However, to prevent this warning from bothering people that like clean pods, I'm more than happy to fix stuff like this.

**Comment by Timac** [comment]
The issue has been partially fixed. There are still the same issue in
- (CGRect)paneViewFrameForPanWithStartLocation:(CGPoint)startLocation currentLocation:(CGPoint)currentLocation bounded:(inout BOOL *)bounded

MSDynamicsDrawerViewController.m:1081:9: warning: Dereference of null pointer (loaded from variable 'paneLocation')
    if (*paneLocation <= paneBoundClosedLocation) {
